# import traceback
#
# from core.core import Core
# import trace
#
# try:
#     # Core.check_or_create_folder(r'C:\Users\workPc\Desktop\New folder (3)', create_if_not_exist=False)
#     # Core.create_config_file('test', 'test.cfg', {'test': False})
#     # test = Core.get_config_by_name('test')
#     # test.read_config()
#     # print(test.get('test1'))
#
#
#     Core.create_logger('test', 'test_logger', 'test')
#     logger = Core.get_logger_by_name('test')
#     logger.info(f'Sadasdasd')
#
#     Core.create_logger('test1', 'test_logger1', 'test')
#     logger1 = Core.get_logger_by_name('test1')
#     logger1.info(f'Sd')
#
# except Exception as e:
#     print(e)
#

